name: Reusable workflow for releasing Meta Box apps (online generator, post type generator and taxonomy generator)
on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      SSH_KNOWN_HOSTS:
        required: true
      SSH_USERNAME:
        required: true
      SERVER_IP:
        required: true
      DIR:
        required: true
      SLACK_WEBHOOK:
        required: true
jobs:
  release:
    name: Release to Meta Box website
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - uses: actions/checkout@master
      - name: Install NPM dependencies
        run: npm install
      - name: Build Javascript
        run: npm run build
      - name: Upload and notify Slack
        run: |
          name=${{ github.event.repository.name }}
          rsync -e "ssh -o StrictHostKeyChecking=no" -r build/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.DIR }}
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          curl -X POST --data-urlencode "payload={\"channel\": \"#meta-box\", \"username\": \"Bot\", \"text\": \"New version $tag for $name has been just released!\", \"icon_emoji\": \":tada:\"}" ${{ secrets.SLACK_WEBHOOK }}
