name: Trigger update on Meta Box Lite

on:
  workflow_dispatch:
    branch:
      - master
  push:
    branch:
      - master
  pull_request:
    types:
      - closed
    branch:
      - master

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger update on Meta Box Lite
        run:
          curl --request POST --url https://api.github.com/repos/wpmetabox/meta-box-lite/actions/workflows/update-from-extensions.yml/dispatches --header 'Authorization:Bearer ${{ secrets.ACCESS_TOKEN }}' --header 'content-type:application/json' --data '{"ref":"master"}'
